version: '3.1'

services:
  mysql_instance:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: money_honey
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "7071:3306"
    volumes:
      - money_honey_db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - moneyhoney

  phpmyadmin_instance:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "7070:80"
    environment:
      PMA_HOST: mysql_instance
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - mysql_instance
    networks:
      - moneyhoney

networks:
  moneyhoney:
    external: true

volumes:
  money_honey_db:
